### ISSUE TITLE
Missing documents

### ISSUE THREAD

**Issue by Author0001** [Xingwei-Warwick/Bayesian-Trans#1]
When conducting the experiment, it was found that file ‘event_rep_cache_cls.npy’ was missing. Can you provide it to me? Thanks a lot！
My email address is  gongjie1130@gmail.com.

**Comment by Xingwei-Tan** [comment]
I'm sorry that I forgot to mention "event_rep_cache_cls.npy" can be obtained by running the encode_event() function of the "ATOMIC_dataset" class.
`atomic = ATOMIC_dataset()`
`atomic.encode_event()`
Thanks for being interested in our work! If you have other questions, please contact me.

**Comment by Author0001** [comment]
Thanks for your reply！
