### ISSUE TITLE
Missing train.tsv

### ISSUE THREAD

**Issue by Ji-Muze** [Xingwei-Warwick/Bayesian-Trans#2]
It seems that the file "train.tsv" is missing in the directory "data/atomic2020/".
Btw, where can I get rgcn_4000d_atomic_prior.pkl?

**Comment by Xingwei-Tan** [comment]
Hi, Ji

Thanks for being interested in our work. I re-uploaded the missing files to the [google drive](https://drive.google.com/drive/folders/1_zddSW2Rbk4fXdp-vjNT4EMpJnm6R1d4?usp=sharing).
Sorry for missing these files in the previous upload. 

Best,
Xingwei
